services:
  mysql:
    image: 'mysql:8'
    container_name: 'database'
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: 'api'
    networks:
      - 'api'
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 100

  api:
    image: 'api:latest'
    container_name: 'api'
    build:
      context: '.'
      dockerfile: './Dockerfile'
    volumes:
      - './src/:/app/src'
    ports:
      - '3000:5000'
    networks:
      - 'api'
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  database:

networks:
  api:
